# Generated by Django 3.1.7 on 2021-03-30 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datlien', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centralhub',
            name='established_on',
        ),
        migrations.RemoveField(
            model_name='hub',
            name='established_on',
        ),
    ]
