# Generated by Django 3.1.7 on 2021-03-30 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datlien', '0002_auto_20210331_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralhub',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='hub',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
