# Generated by Django 3.1.7 on 2021-05-11 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datlien', '0003_auto_20210331_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralhub',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='datlien.state'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='central_hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='datlien.centralhub'),
        ),
    ]
