# Generated by Django 3.1.7 on 2021-05-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datlien', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[(1, 'CENTRAL HUB'), (2, 'HUB'), (3, 'DELIVERY MANAGER'), (4, 'DELIVERY AGENT')], max_length=1),
        ),
    ]
