# Generated by Django 3.1.7 on 2021-05-17 07:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datlien', '0006_auto_20210515_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centralhub',
            name='date',
        ),
        migrations.RemoveField(
            model_name='hub',
            name='date',
        ),
        migrations.AddField(
            model_name='centralhub',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centralhub',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hub',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hub',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='centralhub',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hub',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[(1, 'SUPER USER'), (2, 'CENTRAL HUB'), (3, 'HUB'), (4, 'DELIVERY MANAGER'), (5, 'DELIVERY AGENT')], max_length=1),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='datlien.state')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='centralhub',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='datlien.city'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='datlien.city'),
        ),
    ]
