# Generated by Django 3.1.7 on 2021-05-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datlien', '0008_auto_20210517_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('1', 'SUPER USER'), ('2', 'CENTRAL HUB'), ('3', 'HUB'), ('4', 'DELIVERY MANAGER'), ('5', 'DELIVERY AGENT')], max_length=1),
        ),
    ]
