# Generated by Django 3.1.7 on 2021-05-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datlien', '0012_auto_20210518_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralhub',
            name='base_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='hub',
            name='base_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
