# Generated by Django 3.1.7 on 2021-05-11 09:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datlien', '0004_auto_20210511_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField()),
                ('is_delivered', models.BooleanField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='datlien.hub')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='datlien.hub')),
            ],
        ),
    ]
