# Generated by Django 3.1.7 on 2021-05-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210511_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='is_picked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_recieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delivery',
            name='out_for_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
