# Generated by Django 3.1.7 on 2021-05-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210513_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='is_transit',
            field=models.BooleanField(default=False),
        ),
    ]
