# Generated by Django 3.1.7 on 2021-05-18 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_auto_20210517_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='d_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='delivery',
            name='d_contact',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='delivery',
            name='d_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='delivery',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='delivery',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
