# Generated by Django 3.1.7 on 2021-05-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210518_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='d_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Destination Package Address'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='d_contact',
            field=models.CharField(blank=True, max_length=10, verbose_name='Destination Contact No'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='d_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='Destination Package Owner'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
