# Generated by Django 3.1.7 on 2021-05-18 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datlien', '0012_auto_20210518_2004'),
        ('user', '0011_auto_20210518_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_boy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='datlien.deliveryboy'),
        ),
    ]
