# Generated by Django 3.1.7 on 2021-05-18 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datlien', '0012_auto_20210518_2004'),
        ('user', '0012_delivery_delivery_boy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='datlien.deliveryboy'),
        ),
    ]
