# Generated by Django 3.1.7 on 2021-05-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20210518_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
