# Generated by Django 3.1.7 on 2021-05-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_delivery_is_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
