# Generated by Django 3.1.7 on 2021-05-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_deliveryagent_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='destination_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='destination_contact',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='destination_person',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
