# Generated by Django 3.1.7 on 2021-05-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20210518_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='destination_address',
            field=models.CharField(max_length=100, null=True, verbose_name='Destination Address'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='destination_contact',
            field=models.CharField(max_length=10, null=True, verbose_name='Destination Contact No.'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='destination_person',
            field=models.CharField(max_length=100, null=True, verbose_name='Destination Person'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Weight (In KGs)'),
        ),
    ]
