# Generated by Django 3.1.7 on 2021-05-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20210519_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
