# Generated by Django 3.1.7 on 2021-05-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_delivery_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
